ti-j7xxx: exclude world building for multiconfig k3r5
Issue: LIN1024-3074 LIN1024-3075

Multiconfig k3r5 is only for providing the bootloader tiboot3.bin, it's
no need to build world. To avoid below building issue if run "bitbake
world":
ERROR: Nothing PROVIDES 'virtual/kernel' (but mc:k3r5:layers/oe-core/meta/recipes-core/initrdscripts/initramfs-live-boot_1.0.bb,
mc:k3r5:layers/meta-virtualization/recipes-networking/openvswitch/openvswitch_git.bb,
mc:k3r5:layers/oe-core/meta/recipes-core/initrdscripts/initramfs-live-boot-tiny_1.0.bb DEPENDS on or otherwise requires it)

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>