ti-j7xxx: replace ti-eth-fw with ti-eth-fw-j784s4/j721e
Issue: LIN1024-9545

In commit a04e9fc6 ("ti-linux-fw: Split firmware in to machine packages"),
the package "ti-eth-fw" is empty and files are splited into 3 packages
ti-eth-fw-j721e/j7200/j784s4, so we need to use the specific packages
ti-eth-fw-j784s4/j721e instead of ti-eth-fw to fix the following dnf error:

    User-Agent: falling back to 'libdnf': could not detect OS or basearch
    repo: using cache for: oe-repo
    No match for argument: ti-eth-fw
    Error: Unable to find a match: ti-eth-fw

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>