ti-j7xxx: README: add LICENSE_FLAGS_ACCEPTED += "commercial"
Issue: LIN1024-4982

Since the package edgeai-tiovx-apps is upgraded, it requires ffmpeg and
add LICENSE_FLAGS_ACCEPTED += "commercial" to fix below building issue:

ERROR: Nothing PROVIDES 'ffmpeg' (but meta-edgeai/recipes-tisdk/edgeai-components/edgeai-tiovx-apps.bb DEPENDS on or otherwise requires it)
ffmpeg was skipped: Has a restricted license 'commercial' which is not listed in your LICENSE_FLAGS_ACCEPTED.
rpidistro-ffmpeg PROVIDES ffmpeg but was skipped: Has a restricted license 'commercial' which is not listed in your LICENSE_FLAGS_ACCEPTED.

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>