ti-j7xxx: ti-rtos-firmware: add *_FW_DIR variables setting
Issue: LIN1022-4304

Since the meta-ti layer has been rebased to the latest version, the
ti-rtos-firmware.bb has changed also, add the related *_FW_DIR setting
to fix below building issue:

Log data follows:
| NOTE: Installed into sysroot: []
| NOTE: Skipping as already exists in sysroot: ['opkg-utils', 'quilt-native', 'patch-native', 'pseudo-native',
|'glibc', 'gcc-runtime', 'libtool-native', 'attr-native', 'linux-libc-headers', 'libgcc', 'texinfo-dummy-native', 'gettext-minimal-native']
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_install
| install: missing file operand
| Try 'install --help' for more information.
| WARNING: ti-rtos-firmware/2022.01-r3.1/temp/run.do_install.13626:145 exit 1 from 'install -d ${LEGACY_IPC_FW_DIR}'
| WARNING: Backtrace (BB generated script):
|       #1: do_install, ti-rtos-firmware/2022.01-r3.1/temp/run.do_install.13626, line 145
|       #2: main, ti-rtos-firmware/2022.01-r3.1/temp/run.do_install.13626, line 165
ERROR: Task (ti-rtos-firmware.bb:do_install) failed with exit code '1'

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>