ti-j7xxx: graphic: backport to ti-img-rogue-*_1.15.6133109.bb
Issue: LINUXEXEC-25581

Since the graphic ti-img-rogue-* bb files of the layer meta-ti have been rebased
to 1.18 version, this caused below building issue for gpu features, so we backport
the ti-img-rogue-* bb file to ti-img-rogue-*_1.15.6133109.bb, which are picked from
the TI SDK ti-processor-sdk-linux-j784s4-evm-08_05_00_08. Including the patch file
"0001-compiler-support-OpenEmbedded-nodistro-internal-aarc.patch", which is also
directly picked from TI SDK.

WARNING: ti-img-rogue-driver-1.18.6276027-bb do_fetch: Failed to fetch URL
git://git.ti.com/git/graphics/ti-img-rogue-driver.git;protocol=https;branch=linuxws/dunfell/k5.10/1.18.6276027
_unified_fw_pagesize, attempting MIRRORS if available
ERROR: ti-img-rogue-driver-1.18.6276027-bb do_fetch: Fetcher failure: Unable to find revision
c901804e8221d477983a6f7224a9cdc6e832f050 in branch linuxws/dunfell/k5.10/1.18.6276027_unified_fw_pagesize even from upstream

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>